#ifndef ILI9341_DEMO_H
#define ILI9341_DEMO_H

#include "ILI9341_STM32_Driver.h"


void PERFORMANCE_TEST();
void COUNTING_MULTIPLE_SEGMENTS();
void COUNTING_SINGLE_SEGMENT();
void ALIGNMENT_TEST();
void LINES_EXAMPLE();
void HOLLOW_CIRCLES_EXAMPLE();
void FILLED_CIRCLES_EXAMPLE();
void HOLLOW_RECTANGLES_EXAMPLE();
void FILLED_RECTANGLES_EXAMPLE();
void INDIVIDUAL_PIXEL_EXAMPLE1();
void INDIVIDUAL_PIXEL_EXAMPLE2();
void COLOUR_EXAMPLE();
void SnowTiger();
void Touchscreen_Demo();

#endif
